# Each new term in the Fibonacci sequence is generated by assing the previous
#   two terms. By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#   By considering the terms in the Fibonacci sequence whose values do not
#   exceed four million, find the sum of the even-valued terms.

Cache = {}

def even_fibonacci_sum
  n = 1
  fibonaccis = []
  while fibonacci(n) < 4000000
    number = fibonacci(n)
    fibonaccis << number if number % 2 == 0
    n += 1
  end
  fibonaccis.inject(:+)
end

def fibonacci(n)
  if n == 1
    1
  elsif n == 2
    2
  elsif Cache[n]
    Cache[n]
  else
    Cache[n] = fibonacci(n - 1) + fibonacci(n - 2)
    Cache[n]
  end
end

puts even_fibonacci_sum
